Repository AY2425S1-CS2103T-W13-4/tp, pull requests merged in 2024-10, with the labels that each got.

#52 Add basic skeleton for the tag command
  .gitignore
  bin/main/images/address_book_32.png
  bin/main/images/calendar.png
  bin/main/images/clock.png
  bin/main/images/fail.png
  bin/main/images/help_icon.png
  bin/main/images/info_icon.png
  bin/main/view/CommandBox.fxml
  bin/main/view/DarkTheme.css
  bin/main/view/Extensions.css
  bin/main/view/HelpWindow.css
  bin/main/view/HelpWindow.fxml
  bin/main/view/MainWindow.fxml
  bin/main/view/PersonListCard.fxml
  bin/main/view/PersonListPanel.fxml
  bin/main/view/ResultDisplay.fxml
  bin/main/view/StatusBarFooter.fxml
  bin/test/view/UiPartTest/invalidFile.fxml
  bin/test/view/UiPartTest/validFile.fxml
  bin/test/view/UiPartTest/validFileWithFxRoot.fxml
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story

#55 Implement tag-add command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagAddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TagAddCommandParserTest.java
  src/test/java/seedu/address/model/person/TagTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#72 Add confirmation prompt for delete
  src/main/java/seedu/address/logic/StaticContext.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNCommand.java
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/StaticContextTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteYCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium

#74 Add duplicate handling of tag names and further error handling
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/model/person/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
Labels: type.Enhancement, priority.High

#83 Add more unit tests to cover throwing of exceptions
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#84 Add jonus new handsome photo
  docs/images/jonushzw.png
Labels: type.Task

#89 Update UG with tag-add and tag-delete
  docs/UserGuide.md
Labels: type.Task

#93 Remove duplicate method
  src/main/java/seedu/address/logic/Messages.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Bug

#119 Refactor datetime class and update help command
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterByJobCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/wedding/Date.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/main/java/seedu/address/storage/JsonAdaptedWedding.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonSerializableWeddingBookTest/duplicateWeddingBook.json
  src/test/data/JsonSerializableWeddingBookTest/invalidWeddingBook.json
  src/test/data/JsonSerializableWeddingBookTest/typicalWeddingBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java
  src/test/java/seedu/address/model/WeddingBookTest.java
  src/test/java/seedu/address/model/wedding/DateTest.java
  src/test/java/seedu/address/model/wedding/DatetimeTest.java
  src/test/java/seedu/address/model/wedding/WeddingNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/wedding/WeddingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedWeddingTest.java
  src/test/java/seedu/address/testutil/TypicalWeddings.java
  src/test/java/seedu/address/testutil/WeddingBuilder.java
  src/test/java/seedu/address/testutil/WeddingUtil.java
Labels: priority.Medium

#122 Update UML diagram
  docs/diagrams/CommitActivityDiagram.puml
Labels: type.Task

#132 Update UG & DG
  docs/Documentation.md
  docs/UserGuide.md
  docs/index.md
Labels: severity.VeryLow, alpha-bug

#134 Changed clear command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearAddressBookCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearWeddingBookCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
  src/test/java/seedu/address/logic/commands/TagDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: alpha-bug

#116 Implement list command
  src/main/java/seedu/address/logic/commands/ListWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WeddingCard.java
  src/main/java/seedu/address/ui/WeddingListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeddingListCard.fxml
  src/main/resources/view/WeddingListPanel.fxml
  src/test/data/JsonWeddingBookStorageTest/invalidWeddingBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#137 Change filter to include both find and filterbyjob
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterByJobCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameOrJobContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterByJobCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameOrJobContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#142 Update tag add and tag delete error messages
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
Labels: severity.VeryLow, alpha-bug

#144 Update result display size
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: severity.Low

#143 Update edit command to remove tag editing
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: severity.High, alpha-bug

#154 Change clear command
  src/main/java/seedu/address/logic/StaticContext.java
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNCommand.java
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/test/java/seedu/address/logic/commands/ClearAddressBookCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearWeddingBookCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteYCommandTest.java
Labels: priority.High

#148 Bug fix for editcommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: alpha-bug

#151 Bug fix for AddCommand
  docs/UserGuide.md
  docs/images/deleteWeddingMsg.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: alpha-bug

#153 Update user guide
  docs/UserGuide.md
  docs/images/helpmsg.png
Labels: alpha-bug

#157 Complete view-wedding implementation
  src/main/java/seedu/address/logic/parser/ViewWeddingCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewWeddingCommandParserTest.java
Labels: priority.High

#158 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram2.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task
