Repository AY2425S1-CS2103T-W13-4/tp, pull requests merged in 2024-11, with the labels that each got.

#171 Update add command duplication detection
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Medium, alpha-bug

#190 Update output messages to use static prefix imports
  src/main/java/seedu/address/logic/commands/FilterCommand.java
Labels: alpha-bug

#188 Bug fix: Displays correct output message for weddings that are not created
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
  src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
Labels: alpha-bug

#187 Update output message for wedding doesnt exist
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: alpha-bug

#175 Improve Javadoc comments in TagAddCommand
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
Labels: alpha-bug

#180 Improve Javadoc comments in TagDeleteCommand
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
Labels: alpha-bug

#172 Bug fix for add-wed command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
Labels: alpha-bug

#182 Update UG to reflect new command format
  docs/UserGuide.md
  docs/images/tagDelMsg.png
  docs/images/tagadd2.png
Labels: alpha-bug

#185 Update command word in wedding doesnt exist
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
Labels: alpha-bug

#192 Add faq jonus
  docs/UserGuide.md
  docs/images/addWeddingMsg.png
  docs/images/filterJobMsg.png
  docs/images/filterMsg.png
  docs/images/filterNameMsg.png
Labels: priority.Medium

#195 Add more error handling for view-wed
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
  src/main/java/seedu/address/logic/parser/ViewWeddingCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/wedding/WeddingName.java
  src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewWeddingCommandParserTest.java
Labels: alpha-bug

#197 Update comments in ViewWeddingCommand
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
Labels: alpha-bug

#199 New del wed bug fix
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/test/java/seedu/address/logic/commands/DeleteYCommandTest.java
Labels: severity.Medium, alpha-bug

#204 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui2.png
  docs/index.md
Labels: alpha-bug

#202 Branch bug fix filter command multiple names or jobs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#205 Add view-wed to command summary in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
Labels: alpha-bug

#198 Addcommand alpha bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Job.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteYCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: alpha-bug

#214 Update GUI to fit error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#212 Fix bug in updating the new person in the wedding book
  docs/UserGuide.md
  docs/images/listWeddingMsg.png
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: alpha-bug

#207 bug fix: Delete Command now removes Person from Wedding
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: alpha-bug

#218 ViewWedding handles multiple spacing in user input correctly
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/ViewWeddingCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewWeddingCommandParserTest.java
Labels: alpha-bug

#224 Created two quick starts for techincal and non-technical users
  docs/UserGuide.md
  docs/images/Ui2.png
  docs/images/addMsg.png
  docs/images/deleteMsg.png
  docs/images/deleteNMsg.png
  docs/images/deleteYMsg.png
  docs/images/editMsg.png
  docs/images/editMsg2.png
  docs/images/helpMessage.png
  docs/images/helpmsg.png
  docs/images/johndoe.png
  docs/images/listMsg.png
  docs/index.md
Labels: alpha-bug

#226 Reduce output message length for filter and viewWedding commands
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagAddCommandParser.java
  src/main/java/seedu/address/logic/parser/TagDeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: alpha-bug

#231 Update HelpWindow
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListWeddingCommand.java
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#230 Format messages for command result box
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
  src/test/java/seedu/address/logic/commands/TagDeleteCommandTest.java
Labels: alpha-bug

#232 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ViewWeddingSequenceDiagram.puml
Labels: type.Task

#233 Add known issues
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/addWeddingMsg.png
  docs/images/clearMsg.png
  docs/images/clearMsg1.png
  docs/images/clearMsg2.png
  docs/images/deleteWeddingMsg.png
  docs/images/deleteWeddingNMsg.png
  docs/images/deleteWeddingYMsg.png
  docs/images/filterJobMsg.png
  docs/images/filterMsg1.png
  docs/images/filterMsg2.png
  docs/images/filterNameMsg.png
  docs/images/listMsg.png
  docs/images/listWedding.png
  docs/images/listWeddingMsg.png
  docs/images/tagAddMsg1.png
  docs/images/tagDelMsg.png
  docs/images/tagDelMsg1.png
  docs/images/tagDelMsg2.png
  docs/images/tagadd1.png
  docs/images/tagadd2.png
  docs/images/tagaddMsg.png
  docs/images/tagdeleteMsg.png
  docs/images/tagdeleteMsg1.png
  docs/images/viewWeddingMsg.png
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: priority.High

#234 Update README, DG and UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#237 fix bugs in documentation
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: alpha-bug

#241 Add matching of full name/job in filter
  src/main/java/seedu/address/model/person/NameOrJobContainsKeywordsPredicate.java
Labels: alpha-bug

#242 Update DG
  docs/DeveloperGuide.md
Labels: alpha-bug

#245 Add method in filter command to reduce code duplication
  src/main/java/seedu/address/model/person/NameOrJobContainsKeywordsPredicate.java
Labels: alpha-bug

#250 Update broken links in README
  README.md
Labels: type.Task

#252 Fix bug of invalid prefix being including in parsing
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
Labels: alpha-bug

#247 Add underlining of hyperlinks so readers know that they can be clicked on
  README.md
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java
Labels: type.Task

#257 Fix bug if there is space after invalid prefix
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#256 Improve EditCommand error handling
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: alpha-bug

#258 Standardise naming of KnottyPlanners
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/MainApp.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#248 update error messages to be the approriate ones
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteWeddingCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/wedding/WeddingName.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteWeddingCommandParserTest.java
Labels: alpha-bug

#264 fix broken links in UG, README
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.High, alpha-bug

#267 update mss
  docs/DeveloperGuide.md
Labels: type.Story

#271 bug fix: Add in methods to allow clear-ab and clear-wb to remove wedding participants and wedding tags respectively
  src/main/java/seedu/address/logic/commands/DeleteYCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: alpha-bug

#266 Remove header in README
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task

#272 Add new line character before "Parameters"
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
Labels: alpha-bug

#270 Update new screenshots
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui2.png
  docs/images/addMsg.png
  docs/images/addWeddingMsg.png
  docs/images/clearMsg1.png
  docs/images/clearMsg2.png
  docs/images/deleteMsg.png
  docs/images/deleteNMsg.png
  docs/images/deleteWeddingMsg.png
  docs/images/deleteWeddingNMsg.png
  docs/images/deleteWeddingYMsg.png
  docs/images/deleteYMsg.png
  docs/images/editMsg.png
  docs/images/editMsg2.png
  docs/images/filterMsg1.png
  docs/images/filterMsg2.png
  docs/images/helpmsg.png
  docs/images/listMsg.png
  docs/images/listWedding.png
  docs/images/tagAddMsg1.png
  docs/images/tagAddMsg2.png
  docs/images/tagDelMsg1.png
  docs/images/tagDelMsg2.png
  docs/images/viewWeddingMsg.png
Labels: priority.High, severity.High

#275 Update CodeCov and CI links in readme and index.md
  README.md
  docs/index.md
Labels: alpha-bug

#276 Final bug fixes
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: severity.High, alpha-bug

#278 Issue with JAR file
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#280 Fix spacing in error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#281 bug fix: Add error message when executing deleteNCommand with no pending operation
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/StaticContext.java
  src/main/java/seedu/address/logic/commands/DeleteNCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/ViewWeddingPanel.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/DeleteNCommandTest.java
Labels: priority.Low, alpha-bug

#283 Update sample data
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: alpha-bug

#381 Show error message for duplicate wedding
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Labels: severity.Medium

#380 Update regex for name to accept . and phone to acccept +
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/wedding/WeddingName.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: severity.Low

#392 Update UG Format Consistency
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: severity.Low

#394 Fix vw and filter bug and improve code quality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNCommand.java
  src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListWeddingCommand.java
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: severity.Medium
